### ISSUE TITLE
Invalid typed array length

### ISSUE THREAD

**Issue by andrewdev738** [jnsmalm/pixi3d#76]
I got this error when loading the model:
```
RangeError: Invalid typed array length: 20
    at new Float32Array (&lt;anonymous&gt;)
    at Function.e.from (pixi3d.min.js:17:212373)
    at e.parseBuffer (pixi3d.min.js:17:199160)
    at e.parsePrimitive (pixi3d.min.js:17:204392)
    at pixi3d.min.js:17:203825
    at Array.map (&lt;anonymous&gt;)
    at e.parseMesh (pixi3d.min.js:17:203785)
    at c (pixi3d.min.js:17:206008)
    at c (pixi3d.min.js:17:206399)
    at e.parseModel (pixi3d.min.js:17:206588)
```
glTF version 2.0
Generator: Created using the official Cinema 4D glTF Exporter 1.000x284978

**Comment by jnsmalm** [comment]
Can you share the model so I can debug this error?

**Comment by andrewdev738** [comment]
<a href="https://drive.google.com/file/d/1C9KqbeZjc_6K0mlxKC8Co-S6b2qk8Ucl/view?usp=drivesdk">mesh_tex_test.gltf</a>

**Comment by jnsmalm** [comment]
Thanks for reporting this! I think I have fixed this issue, please test with latest version 1.2.0.

**Comment by andrewdev738** [comment]
Now it's working correctly, thanks!!
